language: python
python:
  - "3.6"
install:
 - pip install tox
 - pip install -r requirements.txt
script:
 - tox
 - pip install .
env:
 - TOXENV=py27-django14
 - TOXENV=py27-django18
 - TOXENV=py27-django19
 - TOXENV=py27-django110
 - TOXENV=py27-django111
 - TOXENV=py36-django18
 - TOXENV=py36-django19
 - TOXENV=py36-django110
 - TOXENV=py36-django111
